// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
import {highlight} from "./minimath-highlight"
export const parser = LRParser.deserialize({
  version: 14,
  states: "#lQVQPOOOhQPO'#CbO![QPO'#CrOhQPO'#CkOOQO'#Ci'#CiO!lQPO'#CiOOQO'#Ca'#CaOOQO'#Cr'#CrOOQO'#Cn'#CnQVQPOOO#^QPO,58|OhQPO,59POhQPO,59PO#qQPO,59VOhQPO,58xOOQO-E6l-E6lO$dQPO1G.kO$nQPO1G.kOOQO1G.q1G.qO$xQPO1G.d",
  stateData: "%Y~OeOS~ORTOVPOWPO^SO`RO~ORSOVPOWPO^SO`RO~OV[OW[OYZOZZO[ZO~ORfX^fX`fXcfX~PyOS^OR]XV]XW]XY]XZ]X[]X^]X`]Xc]X~ORUa^Ua`UacUaaUa~PyOabO~PyOYZORXiVXiWXi^Xi`XicXiaXi~OZXi[Xi~P#xOZZO[ZO~P#xORQi^Qi`QicQi~PyO",
  goto: "!mgPPhPPl!PPP!PPPP!PP!YPP!cPPP!iTVOXSQOXQYPQ]RQ`ZQa[Rc^_UOPRXZ[^_SOPRXZ[^QXOR_XTWOX",
  nodeNames: "⚠ Program Assignment Identifier = Expression UnaryExpression + - BinaryExpression ^ * / PrimaryExpression Number ParenthesizedExpression ( )",
  maxTerm: 22,
  propSources: [highlight],
  skippedNodes: [0],
  repeatNodeCount: 1,
  tokenData: "$}~ReX^!dpq!dxy#Xyz#^z{#c{|#h}!O#m!P!Q#r!Q![#w!_!`$b!c!}$g#Q#R$x#T#o$g#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~!iYe~X^!dpq!d#y#z!d$f$g!d#BY#BZ!d$IS$I_!d$I|$JO!d$JT$JU!d$KV$KW!d&FU&FV!d~#^O`~~#cOa~~#hOZ~~#mOV~~#rOW~~#wO[~~#|Q^~!O!P$S!Q![#w~$VP!Q![$Y~$_P^~!Q![$Y~$gOS~~$lSR~!Q![$g!c!}$g#R#S$g#T#o$g~$}OY~",
  tokenizers: [0],
  topRules: {"Program":[0,1]},
  tokenPrec: 0
})
