// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  Program = 1,
  Assignment = 2,
  Identifier = 3,
  Expression = 5,
  UnaryExpression = 6,
  BinaryExpression = 9,
  PrimaryExpression = 13,
  Number = 14,
  ParenthesizedExpression = 15
